[workspace]
members = [
    "src/abc457",
    "src/abc458",
    "src/abc455",
    "src/awc0073",
    "src/awc0074",
    "src/abc459",
    "src/abc036",
    "src/tessoku-book",
    "src/practice2",
    "src/past202109-open",
    "src/abc185",
    "src/abc460",
    "src/abc431",
    "src/abc153",
    "src/abc121",
    "src/abc176",
    "src/abc083",
    "src/abc148",
    "src/abc297",
    "src/abc397",
    "src/abc331",
    "src/abc364",
    "src/typical90",
    "src/abc360",
    "src/abc349",
    "src/abc461",
    "src/abc315",
    "src/abc229",
    "src/abc138",
    "src/abc136",
    "src/abc084",
    "src/abc081",
    "src/abc042",
    "src/abc398",
    "src/abc462",
    "src/agc026",
    "src/abc463",
    "src/abc103",
    "src/abc450",
    "src/abc464",
    "src/abc089",
    "src/abc200",
    "src/abc141",
    "src/abc129",
    "src/abc190",
    "src/abc465",
    "src/abc167",
    "src/abc158",
    "src/abc466",
    "src/abc159",
    "src/abc467",
    "src/abc069",
    "src/abc468",
    "src/abc447",
    "src/abc469",
    "src/abc186",
    "src/abc178",
    "src/abc470",
    "src/abc102",
    "src/arc122",
    "src/abc196",
    "src/abc471",
    "src/abc149",
    "src/abc180",
    "src/abc166",
    "src/abc090",
    "src/abc472",
    "src/abc473",
    "src/abc171",
    "src/abc212",
    "src/abc213",
    "src/abc214",
    "src/arc229",
    "src/abc474",
    "src/abc215",
    "src/abc216",
    "src/abc475",
    "src/abc443",
    "src/abc442",
    "src/abc423",
    "src/abc406",
    "src/abc404",
    "src/abc399",
    "src/abc387",
    "src/abc385",
    "src/abc476",
    "src/abc382",
    "src/abc379",
    "src/abc477",
    "src/abc378",
    "src/abc377",
    "src/abc376",
    "src/abc375",
    "src/abc374",
]
resolver = "2"
